name: AniFlim
description: "AniFlim"

publish_to: 'none'


version: 1.1.0+4

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  video_player: ^2.9.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  hugeicons: ^0.0.7
  dio: ^5.7.0
  intl: ^0.19.0
  timezone: ^0.9.4
  archive: ^4.0.4
  desktop_window: ^0.4.2
  video_player_media_kit: ^1.0.6
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.5
  media_kit_libs_linux: ^1.2.1
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  brotli: ^0.6.0
  socket_io_client: ^3.1.1
  path_provider: ^2.1.5
  uri: ^1.0.0

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  linux:
    generate: true
    image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
  ios:
    generate: true
    image_path: "assets/icon/icon_ios.png"

flutter:

  uses-material-design: true
