// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG8QkgeroitdnypsyzPsm5VryVnvExV7A',
    appId: '1:165360631941:web:99816495a73033add729ec',
    messagingSenderId: '165360631941',
    projectId: 'aniflim',
    authDomain: 'aniflim.firebaseapp.com',
    storageBucket: 'aniflim.appspot.com',
    measurementId: 'G-11HMWCMN0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaA1otbTSnp1MLe5zoqw4TN8Rn5nBbJAs',
    appId: '1:165360631941:android:3a5ca2de00006d5bd729ec',
    messagingSenderId: '165360631941',
    projectId: 'aniflim',
    storageBucket: 'aniflim.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG8QkgeroitdnypsyzPsm5VryVnvExV7A',
    appId: '1:165360631941:web:f779371f9497ac5ad729ec',
    messagingSenderId: '165360631941',
    projectId: 'aniflim',
    authDomain: 'aniflim.firebaseapp.com',
    storageBucket: 'aniflim.appspot.com',
    measurementId: 'G-QDM6P9PD9B',
  );
}
